
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eat.sm43.dev
  resources:
  - fruits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eat.sm43.dev
  resources:
  - fruits/status
  verbs:
  - get
  - patch
  - update
